version: '3.8'

services:
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile  # o Dockerfile.wordpress si lo llamaste así
    #image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./wordpress:/var/www/html
      # - wordpress-data:/home/app/wordpress
      # - /wordpress:/home/app/wordpress
    depends_on:
      - db

  ftp:
    image: fauria/vsftpd:latest
    container_name: ftp
    ports:
      - "21:21"
    # environment:
    #   WORDPRESS_DB_HOST: db
    #   WORDPRESS_DB_USER: wordpress_user
    #   WORDPRESS_DB_PASSWORD: wordpress_password
    #   WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
